* Version: 2.0.0
* Python: 3.5
* OS: mac/linux/win


### What was wrong?

Please include any of the following that are applicable:

* The code which produced the error
* The full output of the error
* What type of node you were connecting to.


### How can it be fixed?

Fill this section in if you know how this could or should be fixed.
